### ISSUE TITLE
"unplug to lock" does not lock Windows

### ISSUE THREAD

**Issue by Mansarde** [LedgerHQ/bolos-app-win_hello#2]
On Windows 10 Pro 1803 (Build 17134.165) unplugging the Ledger Nano S (or quitting the Hello app on it) won't lock my Windows session.

The setting "unplug to lock" in the Hello app on the device is enabled (i.e. set to "Yes").
I even tried disabling and then re-enabling it and restarting the computer, but no dice. :(

Loggin into a locked session with the Hello app on the device works without any problems though.

Is there maybe some setting in Windows or something else one has to adjust in order for this functionality to work?

Hello app on device: v1.0.1
Hello app on Windows 10: v1.0.0

**Comment by Mansarde** [comment]
Btw. I just noticed that in [ReleaseNote.txt](https://github.com/LedgerHQ/bolos-app-win_hello/blob/master/Companion%20app/ReleaseNote.txt) it says:
> Dynamic lock : locks the workstation on companion device removal (If companion device setting "Unplug to lock" is set to yes, and if companion device was used for last logon)

I have tested with that in mind, but unfortunately the problem remains (i.e. Windows is not locked when unplugging the device).

**Comment by PhilippeBonnaz** [comment]
Thanks for reporting, I'll have a look next week

**Comment by Mansarde** [comment]
Since it has been 6 years and I'm no longer on Windows 10 (and the Ledger firmware changed), I'm closing this.
