### ISSUE TITLE
weird UX

### ISSUE THREAD

**Issue by My1** [LedgerHQ/bolos-app-win_hello#5]
the ledger UX uses the left and right buttons alone to navigate and both together to navigate, however in windows hello the authorize unlock if enabled is using one button to accept and another to deny which is kinda weird in my opinion considering it contradicts the entire UX of ledger

**Comment by TamtamHero** [comment]
Yeah, the app hasn't been updated to our new flow system, as Microsoft said it would deprecate Hello. It has silently backtracked on this topic since, without us noticing. We'll update the app _soon®_

**Comment by My1** [comment]
they have backtracked on it. oh lol, ms playing moving target and Schrödinger yet again, kinda sux

**Comment by TamtamHero** [comment]
Here you go: https://github.com/LedgerHQ/app-windows-hello/commit/d6a6ae7c80e1353e1b484539a3072923338c4222
1.2.0 is available on Ledger Live :+1:
